### ISSUE TITLE
JS File is too large and cannot be published

### ISSUE THREAD

**Issue by ds17f** [christianmittler/shopify-react-extension#1]
Hi!  This project is amazing and exactly what I am looking for.  Unfortunately I'm missing something as it appears that this won't publish due to the file size limits imposed by Shopify. 

I get the following when I try to run the deploy
```
react-embed   │ Running theme check on your Theme app extension...
react-embed   │
react-embed   │ [error]: AssetSizeAppBlockJavaScript
react-embed   │ The file size for 'react-extension.js' (144608 B) exceeds the configured threshold (10000 B)
react-embed   │
react-embed   │ 8  "javascript": "react-extension.js",
react-embed   │ Bundling theme extension react-embed...
```

I checked the version of the `react-extension.js` that is in this repo, and it is around 150kb, much larger than the permitted 10kb.

Is there a workaround for this?  Am I missing something obvious?  It appears that bundling react from a create-react-app application will simply produce a `js` file that is too large.  

Did this work at some point and the rules have changed (on shopify's side)?

**Comment by ds17f** [comment]
See also: https://github.com/Shopify/theme-extension-getting-started/issues/27
And: https://shopify.dev/docs/storefronts/themes/tools/theme-check/checks/asset-size-javascript#options

The latter seems to imply that you can disable this check on a per-theme basis, and that in the CLI version 2x this was not enabled by default.

**Comment by bakikucukcakiroglu** [comment]
Hey, I was also looking for a solution. I was about to try this repo before I saw your issue, as I see it doesn't work so I won't try it. I want to create a theme app extension but I don't want to write pure js, css with liquid. Could you find any workaround? My other plan is to use iframe but I'm not very proficient on iframes and I don't know their capabilities and limitations. You can write me on discord @osenolsanbaki so we can argue on that more.

**Comment by christianmittler** [comment]
Hi, I wasn't active last month as I was on vacation, just saw this issue and your pull request @ds17f. Thank you so much for proposing the solution! With this the file size should not be a problem on deployment anymore.
